### ISSUE TITLE
Broken opam package

### ISSUE THREAD

**Issue by lthms** [janestreet/ppx_optcomp#15]
Dear `ppx_optcomp` maintainers.

If I am not mistaken, you have overwritten the `0.14.3` tag yesterday, which means GitHub created a new archive with different md5 checksum, which then means the `opam` file in `ocaml/opam-repository` is outdated. And indeed, if I download the 0.14.3 archive has not the same checksum as the one mentioned in the opam file in the repository.

If I am right, I would advise against overwritten git tags, for these kind of reasons 😅.

Thanks!

**Comment by n-raymond** [comment]
Hi! Observing the same issue!

Checksum for 0.14.3 is different between the downloaded archive and `opam` file.

```
>  opam info ppx_optcomp.v0.14.3

<><> ppx_optcomp: information on all versions <><><><><><><><><><><><><><><><><>
name                   ppx_optcomp
all-installed-versions v0.14.1
                       [...]
all-versions           v0.14.3

<><> Version-specific details <><><><><><><><><><><><><><><><><><><><><><><><><>
version       v0.14.3
repository    tezos
url.src:      "https://github.com/janestreet/ppx_optcomp/archive/v0.14.3.tar.gz"
url.checksum:
          "md5=2d012df62dd0bc82d2ea4ab25b628992"
          "sha256=3601a4fc1e67b90735985015d12b12168bfacffd529ed17253b1fd512f80bf2f"
          "sha512=73b53dece639aebe20a8c9eaec50f6f491ac8163d96ceab66169d99f9bb50ed9c40c38731cd6e8543dae97c3a45650733d622e5bd4a2db812000c4694c823157"
homepage:     "https://github.com/janestreet/ppx_optcomp"
bug-reports:  "https://github.com/janestreet/ppx_optcomp/issues"
dev-repo:     "git+https://github.com/janestreet/ppx_optcomp.git"
authors:      "Jane Street Group, LLC <opensource@janestreet.com>"
maintainer:   "opensource@janestreet.com"
license:      "MIT"
depends:      "ocaml" {>= "4.08"}
              "base" {>= "v0.14" & < "v0.15"}
              "stdio" {>= "v0.14" & < "v0.15"}
              "dune" {>= "2.0.0"}
              "ppxlib" {>= "0.18.0"}
synopsis      Optional compilation for OCaml
 ```

```
> curl https://github.com/janestreet/ppx_optcomp/archive/v0.14.3.tar.gz | sha256sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   131  100   131    0     0    629      0 --:--:-- --:--:-- --:--:--   632
3bcef471741b97a88c7a155f4cd96e0054c680bcb07b3ca65c8c1c1336aca869  -
```

**Comment by olafhering** [comment]
Such tag update happen on a regular base in various ocaml repositories....

Let me cite the `git tag` man page:

... No. Find and read it yourself and find the relevant paragraph about such wrongdoing...

**Comment by olafhering** [comment]
This also shows a flaw in opam itself.

It should not use mutable git tags, but rather immutable git revisions to refer to a specific version. There is still `git push --force`, which may invalidate a git revision after a while. And I can tell you: such forced pushes happen as well...
