### ISSUE TITLE
Emit line directives

### ISSUE THREAD

**Issue by rgrinberg** [janestreet/ppx_optcomp#3]
Seems like ppx_optcomp isn't doing that and the error messages are all garbled up.

https://github.com/mirage/ocaml-conduit/issues/152

**Comment by lpw25** [comment]
I think this issue is no longer relevant. It could still apply to [ppx_optcomp_old](https://github.com/janestreet/ppx_optcomp_old) but since that is deprecated I'm just going to close the issue.
